job_index:
    path:     /
    defaults: { _controller: "EnsTostainGuillaumeBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsTostainGuillaumeBundle:Job:show" }
    methods:  GET
    requirements:
            id:  \d+

job_new:
    path:     /new
    defaults: { _controller: "EnsTostainGuillaumeBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{token}/edit
    defaults: { _controller: "EnsTostainGuillaumeBundle:Job:edit" }
    methods:  [GET, POST]

job_update:
    path:  /{token}/update
    defaults: { _controller: "EnsTostainGuillaumeBundle:Job:update" }
    methods: POST

job_delete:
    path:     /{token}/delete
    defaults: { _controller: "EnsTostainGuillaumeBundle:Job:delete" }
    methods:  DELETE
