services:
#    ens_tostain_guillaume.example:
#        class: Ens\TostainGuillaumeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    ens.tostainguillaume.admin.category:
        class: Ens\TostainGuillaumeBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, Ens\TostainGuillaumeBundle\Entity\Category, EnsTostainGuillaumeBundle:CategoryAdmin]

    ens.tostainguillaume.admin.job:
        class: Ens\TostainGuillaumeBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null, Ens\TostainGuillaumeBundle\Entity\Job, EnsTostainGuillaumeBundle:JobAdmin]
